kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: lBcbUZNrdyCGFXX3btdCEQqCLHUGHlSYu/JJ9A5expA=
      - identity: {}
